#!/bin/bash

echo "🚀 Smart Email Guardian - Vercel + Replit Deployment Setup"
echo "========================================================"
echo ""

echo "📋 Prerequisites Check:"
echo "1. GitHub repository: https://github.com/ASMAEMISBAH22/email_guard"
echo "2. Vercel account (free): https://vercel.com"
echo "3. Replit account (free): https://replit.com"
echo ""

echo "🔧 Step 1: Deploy Backend on Replit"
echo "-----------------------------------"
echo "1. Go to https://replit.com and sign in"
echo "2. Click 'Create Repl'"
echo "3. Choose 'Import from GitHub'"
echo "4. Enter: https://github.com/ASMAEMISBAH22/email_guard"
echo "5. Select 'Python' as language"
echo "6. Click 'Import from GitHub'"
echo "7. Navigate to the 'backend' folder"
echo "8. Click 'Run' to start the server"
echo "9. Copy your Replit URL (e.g., https://your-repl-name.your-username.repl.co)"
echo ""

echo "🌐 Step 2: Deploy Frontend on Vercel"
echo "------------------------------------"
echo "1. Go to https://vercel.com and sign in"
echo "2. Click 'New Project'"
echo "3. Import your GitHub repository: ASMAEMISBAH22/email_guard"
echo "4. Configure build settings:"
echo "   - Framework Preset: Create React App"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo "5. Click 'Deploy'"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "--------------------------------------"
echo "1. In your Vercel project dashboard, go to 'Settings' → 'Environment Variables'"
echo "2. Add environment variable:"
echo "   Name: REACT_APP_API_URL"
echo "   Value: [Your Replit URL from Step 1]"
echo "   Environment: Production, Preview, Development"
echo "3. Go to 'Deployments' tab and click 'Redeploy'"
echo ""

echo "🔑 Step 4: Get API Key"
echo "----------------------"
echo "1. Visit your Replit URL + '/create-key'"
echo "2. Send POST request with:"
echo "   {"
echo "     \"name\": \"my-app\","
echo "     \"description\": \"Frontend application\""
echo "   }"
echo "3. Copy the returned API key"
echo "4. Use this key in your frontend application"
echo ""

echo "✅ Deployment Complete!"
echo "======================"
echo "Your Smart Email Guardian is now deployed with:"
echo "- Frontend: Vercel (fast, global CDN)"
echo "- Backend: Replit (easy deployment, good for Python)"
echo "- Secure API communication"
echo "- Environment-based configuration"
echo ""

echo "🌍 The application is now accessible to users worldwide!" 